version: '3'
services:
  my-powershell-container:
    image: nickjongens/dockerps
    container_name: dockerps
    environment:
      - CLIENT_ID=<your_client_id>
      - CLIENT_SECRET=<your_client_secret>
      - TENANT_ID=<your_tenant_id>
